apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-two
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/myorg/gitops-argocd.git
    targetRevision: null # will be patched
    path: app-two
  destination:
    server: https://kubernetes.default.svc
    namespace: app-two
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
