apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app-two
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-two
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-two
    spec:
      containers:
      - image: app-two:1.0.0
        name: app-two
        ports:
        - containerPort: 80
