name: Create Deploy PRs

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # To checkout code, commit, push branches
  pull-requests: write # To create PRs

# Use repository variables for Kube versions (Create these in Repo Settings > Secrets and variables > Actions)
env:
  KUBE_VERSION: ${{ vars.KUBE_VERSION || '1.32.1' }} # Default if var not set

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, production]

    # Prevent concurrent runs for the same environment triggered by rapid pushes to main
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.environment }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4.2.2
        with:
          ref: main # Ensure we check out the code from main
          path: main-branch

      - name: Build manifests (${{ matrix.environment }})
        run: |
          ls -alh main-branch
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          alias kustomize=$(pwd)/kustomize
          ./main-branch/scripts/build.sh ${{ matrix.environment }} ${{ env.KUBE_VERSION }}

      - name: Checkout deploy branch (${{ matrix.environment }})
        uses: actions/checkout@v4.2.2
        with:
          ref: deploy/${{ matrix.environment }}
          path: ${{ matrix.environment }}-branch

      - name: Copy build output (${{ matrix.environment }})
        run: |
          find ${{ matrix.environment }}-branch -mindepth 1 -path ${{ matrix.environment }}-branch/.git -prune -o -exec rm -rf {} +
          cp -r main-branch/build/${{ matrix.environment }}/* ${{ matrix.environment }}-branch/

      - name: Create Pull Request (${{ matrix.environment }})
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          path: ${{ matrix.environment }}-branch
          branch: build/${{ matrix.environment }}
          base: deploy/${{ matrix.environment }}
          delete-branch: true
