name: Create Deploy PRs

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # To checkout code, commit, push branches
  pull-requests: write # To create PRs

# Use repository variables for Kube versions (Create these in Repo Settings > Secrets and variables > Actions)
env:
  KUBE_VERSION: ${{ vars.KUBE_VERSION || '1.28.0' }} # Default if var not set

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, production]

    # Prevent concurrent runs for the same environment triggered by rapid pushes to main
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.environment }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout main branch code
        uses: actions/checkout@v4
        with:
          ref: main # Ensure we check out the code from main

      - name: Build Manifests (${{ matrix.environment }})
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          alias kustomize=$(pwd)/kustomize
          ./scripts/build.sh ${{ matrix.environment }} ${{ env.KUBE_VERSION }}

      - name: Create Pull Request (${{ matrix.environment }})
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update ${{ matrix.environment }} manifests from main commit ${{ github.sha }}
          committer: GitHub Actions <actions@github.com> # Optional: Customize committer
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com> # Optional: Use triggering user as author
          signoff: false # Optional: Add Signed-off-by
          # Construct paths and titles directly
          path: build/${{ matrix.environment }}
          base: deploy/${{ matrix.environment }}
          branch: ${{ matrix.environment }}/update-${{ github.sha }}
          title: 🚀 DEPLOYMENT INCOMING [main ${{ github.sha_short }}] --> [deploy/${{ matrix.environment }}]
          delete-branch: true # Delete the head branch after PR merge/close

          # PR Details
          body: |
            Automated PR created by GitHub Actions from commit ${{ github.sha }} on the main branch.

            **Environment:** ${{ matrix.environment }}
            **Triggering Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            Please review the generated manifests.
          # Optional: Add labels, assignees, reviewers
          # labels: automated-pr, ${{ matrix.environment }}
          # assignees: user1,user2
          # reviewers: user1,user2
          draft: false # Set to true to create draft PRs
